### ISSUE TITLE
Bandleaders can create a setlist

### ISSUE THREAD

**Issue by brason** [BouvetNord/it2901_2018_SheetMusic#12]
**Acceptance criteria**
Bandleaders can create a setlist with a name and date, and add scores and events (breaks, speeches, etc..) to it. They can also change the order of items.

- [x] Add setlist dialog (#13) 
- [x] Add score selector dialog (#14)
- [x] Add event dialog (#15)
